### ISSUE TITLE
Matrix 1.3

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1063]
* [x] Finish https://github.com/matrix-org/matrix-spec/pull/1062
* [x] [MSC3604](https://github.com/matrix-org/matrix-spec-proposals/pull/3604)
  * [x] Raise for FCP
  * [x] Complete FCP
  * [x] Write it up
* [x] Try to push through [MSC3267](https://github.com/matrix-org/matrix-spec-proposals/pull/3267) (**not critical for release**)
  * [x] Propose FCP
  * Write it up
  * **De-scoped**
* [x] Write up https://github.com/matrix-org/matrix-spec-proposals/pull/3700
* [x] Write up https://github.com/matrix-org/matrix-spec-proposals/pull/3383
* [x] Write up https://github.com/matrix-org/matrix-spec-proposals/pull/2918
* [x] Write up https://github.com/matrix-org/matrix-spec-proposals/pull/3316
* [x] Changelog cleansing (unify, standardize, etc)
* [x] Ensure above writeups are actually merged
* [x] Write a blog post
* [x] Actual release

**Comment by turt2live** [comment]
Post-release, revert or otherwise undo the relevant parts of https://github.com/matrix-org/matrix-spec/pull/1051

Release date is Thursday, June 16th, 2022.

**Comment by turt2live** [comment]
https://matrix.org/blog/2022/06/16/matrix-v-1-3-release
